{
  "swagger": "2.0",
  "info": {
    "title": "Pagamento Boleto API",
    "version": "v1"
  },
  "schemes": ["https"],
  "host": "api-des.bancovotorantim.com.br",
  "basePath": "/",
  "definitions": {},
  "paths": {"/v1/atacado/boleto/pagamento": {"post": {
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "description": "Serviço responsável pelo pagamento de títulos de cobrança (boletos) para o cliente Atacado.\nSegurança: OAuth (two-legged). Para maiores detalhes do fluxo OAuth de duas pernas, acesse o link: <a href=\"/documentacao#autenticacaolocal\">Documentação OAuth de duas pernas</a>\nHeader: Implementada Trilha de Auditoria\n",
    "parameters": [{
      "in": "body",
      "name": "body",
      "required": true,
      "schema": {
        "$id": "http://example.com/example.json",
        "type": "object",
        "definitions": {},
        "properties": {
          "numeroCNPJRemetente": {"type": "string"},
          "numeroAgenciaRemetente": {"type": "string"},
          "numeroBancoRemetente": {"type": "integer"},
          "tipoPessoaRemetente": {"type": "string"},
          "nomeRemetente": {"type": "string"},
          "numeroContaRemetente": {"type": "string"},
          "numeroBancoFavorecido": {"type": "integer"},
          "numeroCNPJFavorecido": {"type": "string"},
          "nomeFavorecido": {"type": "string"},
          "valorPagamento": {"type": "number"},
          "historico": {"type": "string"},
          "codigoOrigem": {"type": "integer"},
          "codigoFilial": {"type": "integer"},
          "codigoTransacao": {"type": "integer"},
          "nomeUsuario": {"type": "string"},
          "tipoPessoaFavorecido": {"type": "string"},
          "dataMovimento": {"type": "string"},
          "tipoContaRemetente": {"type": "string"},
          "numeroProtocoloCaixa": {"type": "integer"},
          "nomeSegundoRemetente": {"type": "string"},
          "numeroCPFSegundoRemetente": {"type": "string"},
          "linhaDigitavel": {"type": "string"},
          "dataVencimentoBoleto": {"type": "string"},
          "codigoTipoDocumentoCodigoBarra": {"type": "integer"},
          "codigoCanalPagamentoBoleto": {"type": "integer"},
          "valorDocumentoBoleto": {"type": "number"},
          "valorDescontoBoleto": {"type": "number"},
          "valorJuroBoleto": {"type": "number"},
          "valorMultaBoleto": {"type": "number"},
          "valorOutroAcrescimoBoleto": {"type": "number"},
          "siglaSistemaOrigem": {"type": "string"},
          "codigoLancamentoOrigem": {"type": "string"},
          "numeroTituloCIP": {"type": "integer"}
        }
      }
    }],
    "responses": {
      "200": {
        "description": "Retorno.",
        "schema": {
          "$id": "http://example.com/example.json",
          "type": "object",
          "definitions": {},
          "properties": {"protocolo": {
            "type": "object",
            "properties": {
              "numeroProcotoloSolicitacao": {"type": "integer"},
              "codigoStatusProtocoloSolicitacao": {"type": "string"},
              "statusProtocoloSolicitacao": {"type": "string"}
            },
            "required": [
              "codigoStatusProtocoloSolicitacao",
              "statusProtocoloSolicitacao"
            ]
          }}
        },
        "examples": {"application/json": {"protocolo": {
          "numeroProcotoloSolicitacao": 1,
          "codigoStatusProtocoloSolicitacao": "codigoStatusProtocoloSolicitacao",
          "statusProtocoloSolicitacao": "statusProtocoloSolicitacao"
        }}}
      },
      "400": {
        "description": "Request Inválido.",
        "schema": {
          "type": "object",
          "properties": {"fault": {
            "type": "object",
            "properties": {
              "codigo": {"type": "string"},
              "tipo": {"type": "string"},
              "sistemaOrigem": {"type": "string"},
              "mensagem": {"type": "string"},
              "servicoOrigem": {"type": "string"},
              "listaExcecao": {
                "type": "object",
                "properties": {"excecao": {
                  "type": "object",
                  "properties": {
                    "nome": {"type": "string"},
                    "descricao": {
                      "type": "array",
                      "items": {"type": "string"}
                    }
                  },
                  "required": [
                    "nome",
                    "descricao"
                  ]
                }},
                "required": ["excecao"]
              }
            },
            "required": [
              "codigo",
              "tipo",
              "sistemaOrigem",
              "mensagem",
              "servicoOrigem"
            ]
          }}
        },
        "examples": {"application/json": {"fault": {
          "codigo": "30",
          "tipo": "TECNICO",
          "sistemaOrigem": "APIM",
          "mensagem": "erro de validacao de parametros",
          "servicoOrigem": "/v1/atacado/boleto/pagamento"
        }}}
      },
      "401": {
        "description": "Autenticação Inválida",
        "examples": {"application/json": {"fault": {
          "codigo": "990",
          "tipo": "OAuth require 2.0",
          "sistemaOrigem": "APIM",
          "mensagem": "Falha autenticação OAuth.",
          "servicoOrigem": "/v1/atacado/boleto/pagamento"
        }}}
      },
      "403": {
        "description": "Autorização recusada",
        "examples": {"application/json": {
          "requestId": "0000015afaea0172-b16a2",
          "fault": {
            "codigo": "3033",
            "tipo": "TECNICO",
            "sistemaOrigem": "APIM",
            "mensagem": "parametros insuficientes para autenticacao",
            "servicoOrigem": "/v1/atacado/boleto/pagamento"
          }
        }}
      },
      "500": {
        "description": "Erro do Servidor",
        "examples": {"application/json": {
          "requestId": "0000015afaea0172-b5248",
          "fault": {
            "codigo": "5025",
            "tipo": "ParserException",
            "sistemaOrigem": "<nome-do-sistema>",
            "mensagem": "Envelope SOAP com formato incorreto",
            "servicoOrigem": "\"<nome-do-servico>\"",
            "listaExcecao": {"excecao": {
              "nome": "Excecao de backend",
              "descricao": ["Lista de exceção do backend"]
            }}
          }
        }}
      }
    }
  }}}
}